version = 0.1

[default.global.parameters]
region = "us-east-2"

[default.deploy.parameters]
stack_name = "nianza-backend-dev"
region = "us-east-2"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = true
parameter_overrides = "Environment=\"dev\" AdminEmail=\"eja+nianza@banxito.com\" InitialAdminRole=\"super_admin\""

[prod.deploy.parameters]
stack_name = "nianza-backend-prod"
region = "us-east-2"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = true
parameter_overrides = "Environment=\"prod\" AdminEmail=\"eja+nianza@banxito.com\" InitialAdminRole=\"super_admin\""
