const crypto = require("crypto");
const { DynamoDBClient } = require("@aws-sdk/client-dynamodb");
const { DynamoDBDocumentClient, GetCommand, PutCommand, QueryCommand, UpdateCommand } = require("@aws-sdk/lib-dynamodb");
const { json, noContent, error } = require("../../shared/response");

const rawClient = new DynamoDBClient({});
const documentClient = DynamoDBDocumentClient.from(rawClient, {
  marshallOptions: { removeUndefinedValues: true }
});

const CHILDREN_TABLE = process.env.CHILDREN_TABLE;
const VISIT_DEBRIEFS_TABLE = process.env.VISIT_DEBRIEFS_TABLE;

function parseBody(event) {
  if (!event.body) return {};
  return typeof event.body === "string" ? JSON.parse(event.body) : event.body;
}

function claimsFromEvent(event) {
  const claims = event.requestContext?.authorizer?.claims || event.requestContext?.authorizer?.jwt?.claims || {};
  return { userId: claims.sub || "local-acceptance-user" };
}

function childIdFromPath(event) {
  if (event.pathParameters?.childId) return event.pathParameters.childId;
  const path = event.rawPath || event.path || "";
  const match = path.match(/\/visits\/([^/]+)/);
  return match ? decodeURIComponent(match[1]) : null;
}

function truncate(value, maxLength) {
  if (typeof value !== "string") return value;
  const trimmed = value.trim();
  return trimmed.length > maxLength ? trimmed.slice(0, maxLength) : trimmed;
}

async function getChild(userId, childId) {
  const result = await documentClient.send(new GetCommand({ TableName: CHILDREN_TABLE, Key: { userId, childId } }));
  return result.Item || null;
}

// N5 (Parking-Lot Debrief), corrected trigger per Brief v2.16: the post-visit
// card never assumes a visit happened just because nextVisitDate is in the
// past -- it asks first. Whichever branch the parent picks, nextVisitDate is
// cleared here so the card can't re-fire on a stale, unconfirmed date. This
// is a small, deliberate scope: it fixes the "goes stale" problem, not
// visit-tracking accuracy in general (that would need calendar integration,
// explicitly out of scope for this brief).
async function handleConfirmVisit(event) {
  const { userId } = claimsFromEvent(event);
  const childId = childIdFromPath(event);
  if (!childId) return error(400, "INVALID_FIELD", "childId is required.");

  const child = await getChild(userId, childId);
  if (!child) return error(404, "CHILD_NOT_FOUND", "That child was not found on this account.");

  const body = parseBody(event);
  const sawDoctor = body.sawDoctor === true;

  const now = new Date().toISOString();
  const result = await documentClient.send(new UpdateCommand({
    TableName: CHILDREN_TABLE,
    Key: { userId, childId },
    UpdateExpression: "SET nextVisitDate = :null, updatedAt = :now",
    ExpressionAttributeValues: { ":null": null, ":now": now },
    ConditionExpression: "attribute_exists(userId) AND attribute_exists(childId)",
    ReturnValues: "ALL_NEW"
  }));

  return json(200, { child: result.Attributes, offerDebrief: sawDoctor });
}

// The debrief is a transcript of what the PARENT remembers the doctor
// saying -- transcribed client-side via the same Deepgram STT used for chat
// input, never routed through the chat model here. Patricia's only reaction
// is a fixed confirmation, generated by the mobile client, not this
// endpoint -- there is nothing here for a model to interpret.
async function handleCreateDebrief(event) {
  const { userId } = claimsFromEvent(event);
  const childId = childIdFromPath(event);
  if (!childId) return error(400, "INVALID_FIELD", "childId is required.");

  const child = await getChild(userId, childId);
  if (!child) return error(404, "CHILD_NOT_FOUND", "That child was not found on this account.");

  const body = parseBody(event);
  const debriefText = truncate(body.debriefText || body.text, 4000);
  if (!debriefText) return error(400, "INVALID_FIELD", "debriefText is required.");

  const now = new Date().toISOString();
  const visitDate = truncate(body.visitDate, 20) || now;
  const debrief = {
    childId,
    // Sort key embeds the ISO timestamp so QueryCommand + ScanIndexForward:false
    // gives us the most recent debrief directly, same range-query trick used
    // by vitals/milestones elsewhere in this codebase.
    debriefId: `${now}#${crypto.randomUUID()}`,
    visitDate,
    debriefText,
    recordedBy: userId,
    createdAt: now
  };

  await documentClient.send(new PutCommand({ TableName: VISIT_DEBRIEFS_TABLE, Item: debrief }));
  return json(201, { debrief });
}

async function fetchLatestDebrief(childId) {
  const result = await documentClient.send(new QueryCommand({
    TableName: VISIT_DEBRIEFS_TABLE,
    KeyConditionExpression: "childId = :childId",
    ExpressionAttributeValues: { ":childId": childId },
    ScanIndexForward: false,
    Limit: 1
  }));
  return (result.Items || [])[0] || null;
}

async function handleGetLatestDebrief(event) {
  const { userId } = claimsFromEvent(event);
  const childId = childIdFromPath(event);
  if (!childId) return error(400, "INVALID_FIELD", "childId is required.");

  const child = await getChild(userId, childId);
  if (!child) return error(404, "CHILD_NOT_FOUND", "That child was not found on this account.");

  const debrief = await fetchLatestDebrief(childId);
  return json(200, { debrief });
}

exports.handler = async (event) => {
  if (event.httpMethod === "OPTIONS") return noContent();
  if (!CHILDREN_TABLE || !VISIT_DEBRIEFS_TABLE) {
    return error(500, "CONFIGURATION_ERROR", "Visit tables are not configured.");
  }

  const path = event.path || event.rawPath || "";

  try {
    if (event.httpMethod === "POST" && path.endsWith("/confirm")) return handleConfirmVisit(event);
    if (event.httpMethod === "POST" && path.endsWith("/debrief")) return handleCreateDebrief(event);
    if (event.httpMethod === "GET" && path.endsWith("/debrief/latest")) return handleGetLatestDebrief(event);
    return error(404, "NOT_FOUND", "Mobile visits route not found.");
  } catch (err) {
    if (err?.name === "ConditionalCheckFailedException") {
      return error(404, "CHILD_NOT_FOUND", "That child profile could not be found.");
    }
    console.error("mobile visits route failed", err);
    return error(500, "INTERNAL_ERROR", "Something went wrong in the mobile visits service.");
  }
};

exports._private = { fetchLatestDebrief };
